import type { PapersPayload, WorkshopsPayload } from "../types";

export const fixturePayload: PapersPayload = {
  generated_at: "2026-04-15T11:56:08+00:00",
  source_csv: "data/iclr2026/papers.csv",
  columns: [
    "paper_id",
    "paper_url",
    "title",
    "authors",
    "topic_tag",
    "session_title",
    "session_type",
    "session_date",
    "session_start",
    "session_end",
    "room",
    "abstract",
    "project_page",
    "pdf_url",
    "video_url",
    "poster_url",
    "code_url",
    "source_list_url",
    "source_detail_url",
    "schedule_source",
    "scraped_at",
    "status",
    "notes"
  ],
  total_papers: 3,
  topic_tags: [
    "Social Aspects->Trustworthy Machine Learning",
    "Computer Vision->Vision Models & Multimodal"
  ],
  session_dates: ["2026-04-23", "2026-04-24"],
  session_types: ["Oral", "Poster"],
  unresolved_schedule_count: 1,
  papers: [
    {
      paper_id: "p1",
      paper_url: "https://example.test/p1",
      title: "Trustworthy Agents for Long-Horizon Planning",
      authors: "Ada Lovelace · Grace Hopper",
      topic_tag: "Social Aspects->Trustworthy Machine Learning",
      session_title: "",
      session_type: "Poster",
      session_date: "2026-04-23",
      session_start: "11:15",
      session_end: "13:45",
      room: "Pavilion 4",
      abstract: "A paper about trustworthy planning agents.",
      project_page: "https://example.test/project/p1",
      pdf_url: "",
      video_url: "",
      poster_url: "",
      code_url: "https://github.com/example/p1",
      source_list_url: "",
      source_detail_url: "",
      schedule_source: "detail_page",
      scraped_at: "2026-04-15T11:56:08+00:00",
      status: "ok",
      notes: "",
      authors_list: ["Ada Lovelace", "Grace Hopper"],
      topic_tags: ["Social Aspects->Trustworthy Machine Learning"],
      topic_parts: [
        {
          raw: "Social Aspects->Trustworthy Machine Learning",
          group: "Social Aspects",
          name: "Trustworthy Machine Learning"
        }
      ],
      has_schedule: true,
      search_blob: "trustworthy agents for long-horizon planning ada lovelace grace hopper trustworthy machine learning a paper about trustworthy planning agents."
    },
    {
      paper_id: "p2",
      paper_url: "https://example.test/p2",
      title: "Multimodal Memory for Conference Navigation",
      authors: "Geoffrey Hinton",
      topic_tag: "Computer Vision->Vision Models & Multimodal",
      session_title: "Oral Session 2",
      session_type: "Oral",
      session_date: "2026-04-24",
      session_start: "06:30",
      session_end: "09:00",
      room: "Hall A",
      abstract: "A paper about multimodal session memory.",
      project_page: "",
      pdf_url: "https://example.test/p2.pdf",
      video_url: "",
      poster_url: "",
      code_url: "",
      source_list_url: "",
      source_detail_url: "",
      schedule_source: "calendar_exact_title",
      scraped_at: "2026-04-15T11:56:08+00:00",
      status: "ok",
      notes: "",
      authors_list: ["Geoffrey Hinton"],
      topic_tags: ["Computer Vision->Vision Models & Multimodal"],
      topic_parts: [
        {
          raw: "Computer Vision->Vision Models & Multimodal",
          group: "Computer Vision",
          name: "Vision Models & Multimodal"
        }
      ],
      has_schedule: true,
      search_blob: "multimodal memory for conference navigation geoffrey hinton vision models multimodal a paper about multimodal session memory."
    },
    {
      paper_id: "p3",
      paper_url: "https://example.test/p3",
      title: "Schedule Missing Paper",
      authors: "Jane Doe",
      topic_tag: "Social Aspects->Trustworthy Machine Learning",
      session_title: "",
      session_type: "",
      session_date: "",
      session_start: "",
      session_end: "",
      room: "",
      abstract: "No schedule yet.",
      project_page: "",
      pdf_url: "",
      video_url: "",
      poster_url: "",
      code_url: "",
      source_list_url: "",
      source_detail_url: "",
      schedule_source: "",
      scraped_at: "2026-04-15T11:56:08+00:00",
      status: "missing_schedule",
      notes: "missing fields: schedule",
      authors_list: ["Jane Doe"],
      topic_tags: ["Social Aspects->Trustworthy Machine Learning"],
      topic_parts: [
        {
          raw: "Social Aspects->Trustworthy Machine Learning",
          group: "Social Aspects",
          name: "Trustworthy Machine Learning"
        }
      ],
      has_schedule: false,
      search_blob: "schedule missing paper jane doe trustworthy machine learning no schedule yet."
    }
  ]
};

export const emptyWorkshopsPayload: WorkshopsPayload = {
  generated_at: "",
  source_csv: "data/iclr2026/workshops.csv",
  columns: [],
  total_workshops: 0,
  session_dates: [],
  rooms: [],
  unresolved_schedule_count: 0,
  workshops: [],
};

export const workshopFixturePayload: WorkshopsPayload = {
  generated_at: "2026-04-16T08:00:00+00:00",
  source_csv: "data/iclr2026/workshops.csv",
  columns: [
    "workshop_id",
    "workshop_url",
    "title",
    "organizers",
    "event_type",
    "session_date",
    "session_start",
    "session_end",
    "timezone",
    "room",
    "summary",
    "project_page",
    "source_list_url",
    "source_detail_url",
    "scraped_at",
    "status",
    "notes",
  ],
  total_workshops: 2,
  session_dates: ["2026-04-26", "2026-04-27"],
  rooms: ["205", "Ballroom A"],
  unresolved_schedule_count: 0,
  workshops: [
    {
      workshop_id: "w1",
      workshop_url: "https://example.test/workshop/w1",
      title: "1st ICLR Workshop on Time Series in the Age of Large Models",
      organizers: "Arjun Ashok ⋅ Abdul Fatir Ansari ⋅ Elizabeth Fons",
      event_type: "Workshop",
      session_date: "2026-04-26",
      session_start: "05:00",
      session_end: "13:00",
      timezone: "PDT",
      room: "205",
      summary: "This workshop covers time series foundation models and agentic forecasting systems.",
      project_page: "https://example.test/workshop/w1/project",
      source_list_url: "https://example.test/events/workshop",
      source_detail_url: "https://example.test/workshop/w1",
      scraped_at: "2026-04-16T08:00:00+00:00",
      status: "ok",
      notes: "",
      organizers_list: ["Arjun Ashok", "Abdul Fatir Ansari", "Elizabeth Fons"],
      has_schedule: true,
      search_blob:
        "1st iclr workshop on time series in the age of large models arjun ashok abdul fatir ansari elizabeth fons this workshop covers time series foundation models and agentic forecasting systems. 205 workshop",
    },
    {
      workshop_id: "w2",
      workshop_url: "https://example.test/workshop/w2",
      title: "ICLR 2026 Workshop on AI with Recursive Self-Improvement",
      organizers: "Mingchen Zhuge ⋅ AILING ZENG",
      event_type: "Workshop",
      session_date: "2026-04-27",
      session_start: "05:00",
      session_end: "13:00",
      timezone: "PDT",
      room: "Ballroom A",
      summary: "This workshop focuses on reliable recursive self-improvement loops for AI systems.",
      project_page: "",
      source_list_url: "https://example.test/events/workshop",
      source_detail_url: "https://example.test/workshop/w2",
      scraped_at: "2026-04-16T08:00:00+00:00",
      status: "ok",
      notes: "",
      organizers_list: ["Mingchen Zhuge", "AILING ZENG"],
      has_schedule: true,
      search_blob:
        "iclr 2026 workshop on ai with recursive self-improvement mingchen zhuge ailing zeng this workshop focuses on reliable recursive self-improvement loops for ai systems. ballroom a workshop",
    },
  ],
};
